#!/bin/bash
# filepath: ~/workspace/projects/bayesbreak/pin_lock.sh
set -e

INPUT_FILE="requirements.yml"
OUTPUT_FILE="requirements-lock.yml"

if [ ! -f "$INPUT_FILE" ]; then
    echo "Input file '$INPUT_FILE' not found. Please create it before running this script."
    exit 1
fi

# Extract environment name from requirements.yml (if present)
ENV_NAME=$(grep "^name:" "$INPUT_FILE" | awk '{print $2}' | head -n 1)
ENV_NAME="${ENV_NAME:-bayesbreak}"  # Default to 'bayesbreak' if not found

echo "Using environment name: $ENV_NAME"

# Install mamba if not available
if ! command -v mamba &> /dev/null; then
    echo "Installing mamba for faster dependency resolution..."
    conda install -c conda-forge mamba -y
    echo "Mamba installed successfully."
fi

# Create temporary environment name
TEMP_ENV_NAME="${ENV_NAME}-pin-tmp-$(date +%s)"

echo "Creating temporary environment with mamba: $TEMP_ENV_NAME"
echo "This will resolve and install all dependencies..."

# Create environment using mamba (much faster than conda)
mamba env create -f "$INPUT_FILE" -n "$TEMP_ENV_NAME"

# Export the pinned environment
echo "Exporting pinned dependencies to $OUTPUT_FILE"
conda env export -n "$TEMP_ENV_NAME" --no-builds > "$OUTPUT_FILE"

# Clean up temporary environment
echo "Removing temporary environment: $TEMP_ENV_NAME"
conda env remove -y --name "$TEMP_ENV_NAME"

# Fix the exported file to use correct name and remove prefix
echo "Fixing environment name and removing temporary prefix..."
python3 << EOF
import yaml

# Read the exported file
with open('$OUTPUT_FILE', 'r') as f:
    data = yaml.safe_load(f)

# Fix the name
data['name'] = '$ENV_NAME'

# Remove the prefix (it's environment-specific)
if 'prefix' in data:
    del data['prefix']

# Write back the corrected file
with open('$OUTPUT_FILE', 'w') as f:
    yaml.dump(data, f, default_flow_style=False, sort_keys=False)
EOF

# Add header to the lock file
TEMP_FILE=$(mktemp)
cat > "$TEMP_FILE" << EOF
# This file is auto-generated by pin_lock.sh using mamba
# Generated on: $(date '+%Y-%m-%d %H:%M:%S')
# Do not edit manually - regenerate using: ./pin_lock.sh
# 
# To recreate this environment:
#   conda env create -f $OUTPUT_FILE
#   # OR (faster)
#   mamba env create -f $OUTPUT_FILE

EOF

cat "$OUTPUT_FILE" >> "$TEMP_FILE"
mv "$TEMP_FILE" "$OUTPUT_FILE"

echo ""
echo "Pinning completed successfully!"
echo "Pinned environment file: $OUTPUT_FILE"
echo ""
echo "To recreate this exact environment:"
echo "  mamba env create -f $OUTPUT_FILE"
echo "  # OR"
echo "  conda env create -f $OUTPUT_FILE"
echo ""
echo "To update your pinned requirements, run this script again:"
echo "  ./pin_lock.sh"