[build-system]
requires = ["setuptools>=40.8.0",
        "cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "bprseg"
version = "0.0.1"
authors = [
  {name = "Omid Solari", email = "solari@berkeley.edu"},
]
maintainers = [
  {name = "Omid Solari", email = "solari@berkeley.edu"}
]
description = "Bayesian Process Segmentation"
readme = "README.md"
license = {text = "MIT License"}
keywords = ["bayesian", "regression", "change-point estimation"]

[project.urls]
Homepage = "https://github.com/osolari/BPrSeg"
Documentation = "https://github.com/osolari/BPrSeg"
Repository = "https://github.com/osolari/BPrSeg"