[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "BayesBreak"
version = "0.1.0"
description = "BayesBreak toolkit"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "BayesBreak"}
]

# Minimal dependencies - most are handled by conda environment
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "scikit-learn",
    "matplotlib",
    "typer",
    "tqdm",
    "pyyaml",
    "tomlkit",
    "black",
    "jupyterlab",
    "tqdm",
    "pydantic",
    "mkdocs-material",
]

[project.optional-dependencies]
dev = [
    "black",
    "pytest",
    "ipdb",
]

[tool.setuptools]
include-package-data = true  # This activates MANIFEST.in

[tool.setuptools.packages.find]
where = ["."]
include = ["bayesbreak*"]
exclude = ["tests*"]