name: bayesbreak
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - tqdm
  - requests
  - black
  - pytest
  - ipdb
  - numpy
  - scipy
  - pandas
  - statsmodels
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab