#!/usr/bin/env python3
"""Render synchronized BayesBreak implementation records from the canonical JSON."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "shared/handoffs/coding_agent_handoff.json"
TEX_DETAIL = ROOT / "shared/handoffs/coding_agent_handoff.tex"
TEX_SUMMARY = ROOT / "shared/handoffs/implementation_task_registry.tex"
SYNC_MANIFEST = ROOT / "shared/handoffs/SYNC_MANIFEST.json"


def ascii_dashes(text: str) -> str:
    return str(text).replace("—", "--").replace("–", "--").replace("−", "-")


def tex_escape(text: Any) -> str:
    text = ascii_dashes(str(text))
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def split_items(value: str) -> list[str]:
    return [part.strip() for part in str(value).split(";") if part.strip()]


def tex_itemize(items: list[str], *, path_mode: bool = False) -> str:
    if not items:
        return r"\emph{None declared.}"
    lines = [r"\begin{itemize}[leftmargin=1.7em,itemsep=1.5pt,topsep=2pt]"]
    for item in items:
        if path_mode:
            lines.append(r"\item \path{" + ascii_dashes(item) + "}")
        else:
            lines.append(r"\item " + tex_escape(item))
    lines.append(r"\end{itemize}")
    return "\n".join(lines)


def path_list(value: str) -> str:
    return tex_itemize(split_items(value), path_mode=True)


def prose_list(value: str) -> str:
    return tex_itemize([item + ("" if item.endswith(".") else ".") for item in split_items(value)])


def tex_table_rows(records: list[dict[str, Any]], fields: list[str]) -> list[str]:
    rows: list[str] = []
    for record in records:
        cells = [tex_escape(record.get(field, "")) for field in fields]
        rows.append(" & ".join(cells) + r" \\")
    return rows


def render_detail(data: dict[str, Any]) -> str:
    digest = hashlib.sha256(SRC.read_bytes()).hexdigest()
    out: list[str] = [
        r"% Generated by scripts/render_canonical_handoff.py from the canonical JSON.",
        r"\chapter{Complete coding-agent handoff}",
        r"\label{app:coding-handoff}",
        r"\chapterpromise{Implementation specification, module interfaces, test obligations, experiment protocols, and explicit incomplete states rendered from the same source as the standalone handoff.}",
        "",
        r"\begin{statusbox}[Canonical synchronization]",
        "Canonical handoff ID: \\texttt{" + tex_escape(data["handoff_id"]) + "}. Phase: \\texttt{" + tex_escape(data["phase"]) + "}. Canonical JSON SHA-256:",
        r"\path{" + digest + r"}. The book appendix, task registry, standalone Markdown handoff, repository registries, and synchronization manifest are checked mechanically.",
        r"\end{statusbox}",
        "",
        r"\section{Author-fixed scientific scope}",
        tex_escape(data["protected_thesis"]),
        "",
        r"\subsection{Do not change}",
        tex_itemize(data["do_not_change"]),
        "",
        r"\subsection{Non-goals}",
        tex_itemize(data["non_goals"]),
        "",
        r"\section{Repository bootstrap and explicit status}",
        r"\begin{statusbox}[Repository status]",
        r"\textbf{Root.} \path{" + data["repository_bootstrap"]["root"] + r"}\par",
        r"\textbf{Status.} " + tex_escape(data["repository_bootstrap"]["status"]) + r"\par",
        r"\textbf{Environment.} " + tex_escape(data["repository_bootstrap"]["python"]) + r"\par",
        r"\textbf{Use restriction.} " + tex_escape(data["repository_bootstrap"]["install_note"]),
        r"\end{statusbox}",
        r"\paragraph{Required top-level paths.}",
        tex_itemize(data["repository_bootstrap"]["required_top_level"], path_mode=True),
        "",
        r"\subsection{Module ownership}",
        r"\small",
        r"\begin{longtable}{@{}p{0.25\linewidth}p{0.50\linewidth}p{0.16\linewidth}@{}}",
        r"\caption{Approved repository modules and task ownership.}\label{tab:handoff-modules}\\",
        r"\toprule",
        r"\textbf{Path} & \textbf{Responsibility} & \textbf{Tasks}\\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"\textbf{Path} & \textbf{Responsibility} & \textbf{Tasks}\\",
        r"\midrule",
        r"\endhead",
    ]
    for rec in data["module_ownership"]:
        out.append(r"\path{" + rec["path"] + "} & " + tex_escape(rec["responsibility"]) + " & " + tex_escape(rec["tasks"]) + r" \\")
    out.extend([r"\bottomrule", r"\end{longtable}", r"\normalsize", ""])

    out.extend([r"\section{Configuration keys, commands, and schemas}"])
    out.append(r"\subsection{Configuration keys}")
    for group, keys in data["configuration_keys"].items():
        out.append(r"\paragraph{" + tex_escape(group.replace("_", " ").title()) + r".}")
        out.append(tex_itemize(keys, path_mode=True))
    out.append(r"\subsection{Commands}")
    for group, commands in data["commands"].items():
        out.append(r"\paragraph{" + tex_escape(group.replace("_", " ").title()) + r".}")
        out.append(tex_itemize(commands, path_mode=True))
    out.append(r"\subsection{Required schema fields}")
    for schema, fields in data["data_schemas"].items():
        out.append(r"\paragraph{" + tex_escape(schema.replace("_", " ").title()) + r".}")
        out.append(tex_itemize(fields, path_mode=True))

    out.extend(["", r"\section{Exact files, interfaces, invariants, and acceptance tests}"])
    out.append("The task cards below are generated directly from the canonical handoff. No task is represented as complete merely because its interface appears in the repository skeleton.")
    for task in data["tasks"]:
        out.extend([
            "",
            r"\begin{statusbox}[" + tex_escape(task["id"]) + r"]",
            r"\textbf{Task.} " + tex_escape(task["title"]) + r"\par",
            r"\textbf{Files.}",
            path_list(task["files"]),
            r"\textbf{Interfaces.}",
            path_list(task["interfaces"]),
            r"\textbf{Theory-to-code invariants.}",
            prose_list(task["invariants"]),
            r"\textbf{Dependencies.} " + tex_escape(task["depends_on"]) + r"\par",
            r"\textbf{Acceptance.} " + tex_escape(task["acceptance"]),
            r"\end{statusbox}",
        ])

    out.extend(["", r"\section{Stage sequence}", r"\small", r"\begin{longtable}{@{}p{0.08\linewidth}p{0.25\linewidth}p{0.26\linewidth}p{0.31\linewidth}@{}}", r"\caption{Implementation and validation sequence.}\label{tab:handoff-stages}\\", r"\toprule", r"\textbf{Stage} & \textbf{Purpose} & \textbf{Tasks} & \textbf{Advance criterion}\\", r"\midrule", r"\endfirsthead", r"\toprule", r"\textbf{Stage} & \textbf{Purpose} & \textbf{Tasks} & \textbf{Advance criterion}\\", r"\midrule", r"\endhead"])
    for stage in data["stage_sequence"]:
        out.append(tex_escape(stage["stage"]) + " & " + tex_escape(stage["title"]) + " & " + tex_escape(stage["tasks"]) + " & " + tex_escape(stage["advance"]) + r" \\")
    out.extend([r"\bottomrule", r"\end{longtable}", r"\normalsize", ""])

    out.extend([r"\section{Experiment matrix and output ownership}"])
    out.append("Each experiment driver owns a machine-readable run registry, configuration set, raw metric records, and figure or table target. Populated archived values remain read-only. Corrected runs receive a new result ID and a parent pointer.")
    for exp in data["experiments"]:
        out.extend([
            "",
            r"\subsection{" + tex_escape(exp["id"] + " -- " + exp["title"]) + r"}",
            r"\textbf{Claims.} " + tex_escape(exp["claims"]) + r"\par",
            r"\textbf{Status.} " + tex_escape(exp["status"]) + r"\par",
            r"\textbf{Hypothesis.} " + tex_escape(exp.get("hypothesis", "")) + r"\par",
            r"\textbf{Competing explanation.} " + tex_escape(exp.get("competing", "")) + r"\par",
            r"\textbf{Design.} " + tex_escape(exp.get("design", "")) + r"\par",
            r"\textbf{Metrics.} " + tex_escape(exp.get("metrics", "")) + r"\par",
            r"\textbf{Repetition and uncertainty.} " + tex_escape(exp.get("uncertainty", "")) + r"\par",
            r"\textbf{Dependencies.} " + tex_escape(exp["dependencies"]) + r"\par",
            r"\textbf{Output.} " + tex_escape(exp["output"]),
        ])

    out.extend(["", r"\section{Claim status map}", r"\small", r"\begin{longtable}{@{}p{0.13\linewidth}p{0.47\linewidth}p{0.32\linewidth}@{}}", r"\caption{Claim status used by the implementation and experiment records.}\label{tab:handoff-claims}\\", r"\toprule", r"\textbf{ID} & \textbf{Claim} & \textbf{Status}\\", r"\midrule", r"\endfirsthead", r"\toprule", r"\textbf{ID} & \textbf{Claim} & \textbf{Status}\\", r"\midrule", r"\endhead"])
    for claim in data["claims"]:
        out.append(tex_escape(claim["claim_id"]) + " & " + tex_escape(claim["claim"]) + " & " + tex_escape(claim["status"]) + r" \\")
    out.extend([r"\bottomrule", r"\end{longtable}", r"\normalsize", ""])

    out.extend([r"\section{Executed-result interpretation map}", r"\small", r"\begin{longtable}{@{}p{0.15\linewidth}p{0.20\linewidth}p{0.25\linewidth}p{0.31\linewidth}@{}}", r"\caption{Result provenance and permitted scientific interpretation.}\label{tab:handoff-results}\\", r"\toprule", r"\textbf{ID} & \textbf{Class} & \textbf{Interpretation status} & \textbf{Release action}\\", r"\midrule", r"\endfirsthead", r"\toprule", r"\textbf{ID} & \textbf{Class} & \textbf{Interpretation status} & \textbf{Release action}\\", r"\midrule", r"\endhead"])
    for result in data["results"]:
        out.append(tex_escape(result["result_id"]) + " & " + tex_escape(result["classification"]) + " & " + tex_escape(result["interpretation_status"]) + " & " + tex_escape(result["release_action"]) + r" \\")
    out.extend([r"\bottomrule", r"\end{longtable}", r"\normalsize", ""])

    out.extend([r"\section{Test matrix}", r"\small", r"\begin{longtable}{@{}p{0.14\linewidth}p{0.43\linewidth}p{0.35\linewidth}@{}}", r"\caption{Required test classes.}\label{tab:handoff-tests}\\", r"\toprule", r"\textbf{Class} & \textbf{Scope} & \textbf{Acceptance}\\", r"\midrule", r"\endfirsthead", r"\toprule", r"\textbf{Class} & \textbf{Scope} & \textbf{Acceptance}\\", r"\midrule", r"\endhead"])
    for rec in data["test_matrix"]:
        out.append(tex_escape(rec["class"]) + " & " + tex_escape(rec["scope"]) + " & " + tex_escape(rec["acceptance"]) + r" \\")
    out.extend([r"\bottomrule", r"\end{longtable}", r"\normalsize", ""])

    out.extend([r"\section{Logging, provenance, and resources}", r"\subsection{Required run records}", tex_itemize(data["logging_and_provenance"]), r"\subsection{Resource planning}", tex_itemize(data["resource_expectations"]), ""])

    out.extend([r"\section{Explicit failure states}"])
    for rec in data["failure_states"]:
        out.extend([
            r"\begin{cautionbox}[" + tex_escape(rec["id"]) + r"]",
            r"\textbf{Condition.} " + tex_escape(rec["condition"]) + r"\par",
            r"\textbf{Required behavior.} " + tex_escape(rec["required_behavior"]),
            r"\end{cautionbox}",
        ])

    out.extend(["", r"\section{Definition of done}", tex_itemize(data["definition_of_done"])])
    return "\n".join(out) + "\n"


def render_summary(data: dict[str, Any]) -> str:
    out = [
        r"% Generated from shared/handoffs/coding_agent_handoff.json.",
        r"\small",
        r"\begin{longtable}{@{}p{0.16\linewidth}p{0.37\linewidth}p{0.37\linewidth}@{}}",
        r"\caption{Implementation task registry. Detailed files, interfaces, and invariants are in Appendix~\ref{app:coding-handoff}.}\label{tab:code-tasks}\\",
        r"\toprule",
        r"\textbf{ID} & \textbf{Work item} & \textbf{Acceptance criterion}\\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"\textbf{ID} & \textbf{Work item} & \textbf{Acceptance criterion}\\",
        r"\midrule",
        r"\endhead",
    ]
    for task in data["tasks"]:
        out.append(r"\texttt{" + tex_escape(task["id"]) + "} & " + tex_escape(task["title"]) + " & " + tex_escape(task["acceptance"]) + r" \\")
    out.extend([r"\bottomrule", r"\end{longtable}", r"\normalsize"])
    return "\n".join(out) + "\n"


def md_list(items: list[str]) -> list[str]:
    return [f"- {ascii_dashes(item)}" for item in items]


def render_markdown(data: dict[str, Any]) -> str:
    digest = hashlib.sha256(SRC.read_bytes()).hexdigest()
    lines: list[str] = [
        "# BayesBreak coding-agent handoff",
        "",
        f"Canonical handoff: `{data['handoff_id']}`",
        f"Phase: `{data['phase']}`",
        f"Canonical JSON SHA-256: `{digest}`",
        "",
        "## Author-fixed scientific scope",
        "",
        ascii_dashes(data["protected_thesis"]),
        "",
        "## Do not change",
        "",
        *md_list(data["do_not_change"]),
        "",
        "## Non-goals",
        "",
        *md_list(data["non_goals"]),
        "",
        "## Repository bootstrap",
        "",
        f"- Root: `{data['repository_bootstrap']['root']}`",
        f"- Status: {data['repository_bootstrap']['status']}",
        f"- Environment: {data['repository_bootstrap']['python']}",
        f"- Use restriction: {data['repository_bootstrap']['install_note']}",
        "",
        "### Required top-level paths",
        "",
        *[f"- `{x}`" for x in data["repository_bootstrap"]["required_top_level"]],
        "",
        "## Module ownership",
        "",
        "| Path | Responsibility | Tasks |",
        "|---|---|---|",
    ]
    for rec in data["module_ownership"]:
        lines.append(f"| `{rec['path']}` | {ascii_dashes(rec['responsibility'])} | {rec['tasks']} |")

    lines += ["", "## Configuration keys", ""]
    for group, keys in data["configuration_keys"].items():
        lines += [f"### {group.replace('_',' ').title()}", "", *[f"- `{x}`" for x in keys], ""]

    lines += ["## Commands", ""]
    for group, commands in data["commands"].items():
        lines += [f"### {group.replace('_',' ').title()}", "", *[f"- `{x}`" for x in commands], ""]

    lines += ["## Required schema fields", ""]
    for schema, fields in data["data_schemas"].items():
        lines += [f"### {schema.replace('_',' ').title()}", "", *[f"- `{x}`" for x in fields], ""]

    lines += ["## Tasks", ""]
    for task in data["tasks"]:
        lines += [
            f"### {task['id']} -- {ascii_dashes(task['title'])}",
            "",
            f"**Files:** `{task['files']}`",
            "",
            f"**Interfaces:** `{task['interfaces']}`",
            "",
            f"**Invariants:** {ascii_dashes(task['invariants'])}",
            "",
            f"**Dependencies:** {task['depends_on']}",
            "",
            f"**Acceptance:** {ascii_dashes(task['acceptance'])}",
            "",
        ]

    lines += ["## Stage sequence", "", "| Stage | Purpose | Tasks | Advance criterion |", "|---|---|---|---|"]
    for stage in data["stage_sequence"]:
        lines.append(f"| {stage['stage']} | {ascii_dashes(stage['title'])} | {stage['tasks']} | {ascii_dashes(stage['advance'])} |")

    lines += ["", "## Experiments", ""]
    for exp in data["experiments"]:
        lines += [
            f"### {exp['id']} -- {ascii_dashes(exp['title'])}",
            "",
            f"**Claims:** {exp['claims']}",
            "",
            f"**Status:** {ascii_dashes(exp['status'])}",
            "",
            f"**Hypothesis:** {ascii_dashes(exp.get('hypothesis',''))}",
            "",
            f"**Competing explanation:** {ascii_dashes(exp.get('competing',''))}",
            "",
            f"**Design:** {ascii_dashes(exp.get('design',''))}",
            "",
            f"**Metrics:** {ascii_dashes(exp.get('metrics',''))}",
            "",
            f"**Repetition and uncertainty:** {ascii_dashes(exp.get('uncertainty',''))}",
            "",
            f"**Dependencies:** {exp['dependencies']}",
            "",
            f"**Output:** {ascii_dashes(exp['output'])}",
            "",
        ]

    lines += ["## Claim status map", "", "| ID | Claim | Status |", "|---|---|---|"]
    for claim in data["claims"]:
        lines.append(f"| {claim['claim_id']} | {ascii_dashes(claim['claim'])} | {ascii_dashes(claim['status'])} |")

    lines += ["", "## Result interpretation map", "", "| ID | Classification | Interpretation status | Release action |", "|---|---|---|---|"]
    for result in data["results"]:
        lines.append(f"| {result['result_id']} | {ascii_dashes(result['classification'])} | {ascii_dashes(result['interpretation_status'])} | {ascii_dashes(result['release_action'])} |")

    lines += ["", "## Test matrix", "", "| Class | Scope | Acceptance |", "|---|---|---|"]
    for rec in data["test_matrix"]:
        lines.append(f"| {rec['class']} | {ascii_dashes(rec['scope'])} | {ascii_dashes(rec['acceptance'])} |")

    lines += ["", "## Logging and provenance", "", *md_list(data["logging_and_provenance"]), "", "## Resource expectations", "", *md_list(data["resource_expectations"]), "", "## Failure states", ""]
    for rec in data["failure_states"]:
        lines += [f"### {rec['id']}", "", f"**Condition:** {ascii_dashes(rec['condition'])}", "", f"**Required behavior:** {ascii_dashes(rec['required_behavior'])}", ""]

    lines += ["## Definition of done", "", *md_list(data["definition_of_done"]), ""]
    return "\n".join(lines)


def render_sync_manifest(data: dict[str, Any]) -> str:
    digest = hashlib.sha256(SRC.read_bytes()).hexdigest()
    manifest = {
        "handoff_id": data["handoff_id"],
        "phase": data["phase"],
        "canonical_json": str(SRC.relative_to(ROOT)),
        "canonical_json_sha256": digest,
        "generated_files": [
            str(TEX_DETAIL.relative_to(ROOT)),
            str(TEX_SUMMARY.relative_to(ROOT)),
        ],
        "counts": {
            "tasks": len(data["tasks"]),
            "experiments": len(data["experiments"]),
            "claims": len(data["claims"]),
            "results": len(data["results"]),
            "failure_states": len(data["failure_states"]),
            "stages": len(data["stage_sequence"]),
        },
    }
    return json.dumps(manifest, indent=2) + "\n"


def main() -> None:
    data = json.loads(SRC.read_text())
    TEX_DETAIL.write_text(render_detail(data))
    TEX_SUMMARY.write_text(render_summary(data))
    SYNC_MANIFEST.write_text(render_sync_manifest(data))
    print(
        f"rendered {len(data['tasks'])} tasks, {len(data['experiments'])} experiments, "
        f"{len(data['claims'])} claims, and {len(data['results'])} results"
    )


if __name__ == "__main__":
    main()
