name: bayesbreak
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.10,<3.13
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - typer
  - tqdm
  - pytest
  - mypy
  - ruff
  - pre-commit
  - pyyaml
  - tomlkit
  - black
  - jupyterlab
  - tqdm
  - pydantic
  - mkdocs-material
  - pip