name: Conda Package Validation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniforge-variant: Miniforge3
          python-version: "3.11"

      - name: Install conda-build
        run: mamba install -y conda-build

      - name: Build conda package
        run: |
          conda config --set anaconda_upload no
          conda build conda-recipe --output-folder conda-bld --channel conda-forge
